### ISSUE TITLE
Allow users to be named something else than 'sebastian'

### ISSUE THREAD

**Issue by binwiederhier** [flix-/pam_openssh_x509#7]
I must say, this is a first: 
> Make sure there is a local user 'sebastian'

You should be able to compile without having to have a local user named 'sebastian'.

**Comment by binwiederhier** [comment]
Also: this made me laugh soooo hard :smile: :laughing:

**Comment by flix-** [comment]
This is maybe a bit misleading. Of course you dont need to have a local user 'sebastian' to run the modules... :D I setup a lot of preconfigured files (certificates, configs, ldifs) in order to make a first installation as easy as possible for people that dont have a running PKI, LDAP server etc. yet so that they can get familiar how the system is working. Of course if you wanna use it for serious reason you will have your own certificates, users, ldap configuration. The prerequisite that you need a local user 'sebastian' only applies if you wanna install a test system with the configurations delivered...

I should mention this more precise somewhere :)
